config_version: 1.1.9
guild:
  promote:
    # 金币升级公式
    money_formula: '1000*(1+0.05)^%GUILD_MEMBER_COUNT%'
    # 金币最大能升级到的人数
    money_max_member_count: 10
    # 点券升级公式
    point_formula: '5*(1+0.05)^%GUILD_MEMBER_COUNT%'
    # 金币最大能升级到的人数
    point_max_member_count: 50
  def_icon:
    material: APPLE
    durability: 0
  icon:
    items:
      '1':
        material: STONE
        durability: 0
        display_name: '&f石头'
        lores:
          - 'l1'
        cost:
          type: POINTS
          amount: 1000
      '2':
        material: DIAMOND
        durability: 0
        cost:
          type: MONEY
          amount: 1000
        display_name: '&f钻石'
        lores:
          - 'l1'
  donate_min_money: 10000
  def_max_admin_count: 3
  #rank_formula: '%LEVEL% + %%'
  request:
    join:
      timeout: 3600 # 秒，请求加入超时
    invite:
      timeout: 300 # 秒，邀请超时
  announcement:
    split_char: '#' # 换行符
    max_count: 5 # 最大公告数量
  def_max_member_count: 5
  create:
    name_regex: '[\\u4e00-\\u9fa5_a-zA-Z0-9_§]{1,10}' # 注意转义
    name_not_valid_msg: '&c宗门名只能由中文英文数字组成, 且长度大于1小于10个字符.'
    colored_no_per_msg: "&c你没有权限使用彩色代码作为宗门名."
    cost:
      money:
        amount: 1000
        enabled: true
      points:
        amount: 100
        enabled: true
      item:
        enabled: true
        amount: 1
        key_lore: '创建宗门'
gui:
  # 全局
  global:
    # 宗门信息
    guild_info:
      display_name: '&f宗门信息'
      lores:
        - '&b『Top.%GUILD_RANKING%&b』'
        - ' '
        - '&7- &d宗主 &b▹ &d%GUILD_OWNER%'
        - '&7- &a人数 &b▹ &a%GUILD_MEMBER_COUNT%/%GUILD_MAX_MEMBER_COUNT%'
        - '&7- &eGDP &b▹ &e%GUILD_BALANCE%'
        - '&7- &9创建时间 &b▹ &9%GUILD_CREATION_TIME%'
  main_gui:
    # 排行榜
    ranking_list:
      display_name: '&f%GUILD_NAME%'
      lores:
        - '&b『&bTop.%GUILD_RANKING%&b』'
        - ' '
        - '&7- &d宗主 &b▹ &d%GUILD_OWNER%'
        - '&7- &a人数 &b▹ &a%GUILD_MEMBER_COUNT%/%GUILD_MAX_MEMBER_COUNT%'
        - '&7- &eGDP &b▹ &e¥%GUILD_BALANCE%'
        - '&7- &9创建时间 &b▹ &9%GUILD_CREATION_TIME%'
  mine_gui:
    player_info:
      display_name: '&f个人信息'
      lores:
        - '&b• &7%player_name%&b •'
        - ' '
        - '&7- &a所在宗门 &b▹ &a%GUILD_NAME%'
        - '&7- &d职务 &b▹ &d%GUILD_MEMBER_PER%'
        - '&7- &e金币贡献 &b▹ &e%GUILD_MEMBER_DONATE_MONEY%'
        - '&7- &9入宗时间 &b▹ &9%GUILD_MEMBER_JOIN_TIME%'
