config_version: 1.3.6
guild:
  # 排行榜
  ranking_list:
    # 计算公式
    formula: '%GUILD_MONEY%*0.3+%GUILD_POINTS%*0.5+%GUILD_MEMBER_COUNT%*0.2'
  # 全员传送
  tp_all:
    # 允许发送请求的世界
    allowed_send_worlds:
      - '*'
    # 允许接收请求的世界
    allowed_receive_worlds:
      - '*'
    # 请求超时时间
    timeout: 15
    # 传送间隔限制
    interval: 60
    # 计次毫秒
    shift_count_interval: 1000
    # 触发次数
    shift_count: 3
    # 消耗宗门银行金币
    cost:
      money: 500
      enabled: true
  promote:
    # 金币升级公式
    money_formula: '1000*(1+0.05)^%GUILD_MAX_MEMBER_COUNT%'
    # 金币最大能升级到的人数
    money_max_member_count: 10
    # 点券升级公式
    point_formula: '5*(1+0.05)^%GUILD_MAX_MEMBER_COUNT%'
    # 金币最大能升级到的人数
    point_max_member_count: 50
  # 默认图标
  def_icon:
    material: APPLE
    durability: 0
  # 宗门图标商店
  icon_shop:
    items:
      '1':
        material: STONE
        durability: 0
        display_name: '&f石头'
        lores:
          - '&7- &e花费 &b▹ 点券/金币'
          - '&7- &d价格 &b▹ &d1000/500'
        cost:
          points:
            amount: 1000
            enabled: true
          money:
            amount: 500
            enabled: false
      '2':
        material: DIAMOND
        durability: 0
        display_name: '&d钻石'
        lores:
          - '&7- &e花费 &b▹ 点券/金币'
          - '&7- &d价格 &b▹ &d1000/1000'
        cost:
          points:
            amount: 1000
            enabled: true
          money:
            amount: 1000
            enabled: true
  # 赞助
  donate:
    # 最小点券
    min_points: 1
    # 最小金币
    min_money: 10000
  # 默认最大管理员数量
  def_max_admin_count: 3
  # 默认最大成员数
  def_max_member_count: 5
  # 请求
  request:
    join:
      timeout: 3600 # 秒，请求加入超时
  # 公告
  announcement:
    def:
      - '&d欢迎加入本宗门~'
    # 换行符
    split_char: '#'
    # 最大公告数量
    max_count: 5
  # 创建
  create:
    # 宗门名正则表达式
    name_regex: '[\u4e00-\u9fa5_a-zA-Z0-9_§]{1,10}'
    # 未通过表达式提示消息
    name_not_valid_msg: '&c宗门名只能由中文英文数字组成, 且长度大于1小于10个字符.'
    #
    colored_no_per_msg: "&c你没有权限使用彩色代码作为宗门名."
    # 消费
    cost:
      money:
        amount: 1000
        enabled: true
      points:
        amount: 100
        enabled: true
      item:
        enabled: true
        amount: 1
        key_lore: '创建宗门'
gui:
  # 全局
  global:
    # 宗门信息
    guild_info:
      display_name: '&f宗门信息'
      lores:
        - '&b『Top.%GUILD_RANKING%&b』'
        - ' '
        - '&7- &d宗主 &b▹ &d%GUILD_OWNER%'
        - '&7- &a人数 &b▹ &a%GUILD_MEMBER_COUNT%/%GUILD_MAX_MEMBER_COUNT%'
        - '&7- &e金币储备 &b▹ &e%GUILD_MONEY%'
        - '&7- &e点券储备 &b▹ &e%GUILD_POINTS%'
        - '&7- &9创建时间 &b▹ &9%GUILD_CREATION_TIME%'
  main_gui:
    # 排行榜
    ranking_list:
      display_name: '&f%GUILD_NAME%'
      lores:
        - '&b『&bTop.%GUILD_RANKING%&b』'
        - ' '
        - '&7- &d宗主 &b▹ &d%GUILD_OWNER%'
        - '&7- &a人数 &b▹ &a%GUILD_MEMBER_COUNT%/%GUILD_MAX_MEMBER_COUNT%'
        - '&7- &e金币储备 &b▹ &e%GUILD_MONEY%'
        - '&7- &e点券储备 &b▹ &e%GUILD_POINTS%'
        - '&7- &9创建时间 &b▹ &9%GUILD_CREATION_TIME%'
  mine_gui:
    # 个人信息
    player_info:
      display_name: '&f个人信息'
      lores:
        - '&b• &7%player_name%&b •'
        - ' '
        - '&7- &a所在宗门 &b▹ &a%GUILD_NAME%'
        - '&7- &d职务 &b▹ &d%GUILD_MEMBER_PER%'
        - '&7- &e金币贡献 &b▹ &e%GUILD_MEMBER_DONATE_MONEY%'
        - '&7- &e金币贡献 &b▹ &e%GUILD_MEMBER_DONATE_POINTS%'
        - '&7- &9入宗时间 &b▹ &9%GUILD_MEMBER_JOIN_TIME%'
