# 本插件所有游戏版本（1.7.10-1.15）使用UTF-8编码
version: 2.0.0
test: AMBIENT_CAVE
# 是否开启数据统计
metrics_enabled: true
papi:
  # 没有可供显示的字符串时显示的字符串
  non_str: '-'
# gui设置
gui:
  # 默认
  default:
    # 是否默认使用颜色转换
    colored: true
    # 是否默认使用公会内部变量
    use_gp: true
    # 是否默认使用PAPI
    use_papi: false
guild:
  default_icon:
    material: APPLE
    data: 0
    first_lore: '' # 用于支持 SX-Attribute 的物品
  # 排行榜
  ranking_list:
    # 计算公式，可用变量：
    # {guild_money} 公会金币储备
    # {guild_points} 公会点券储备
    # {guild_member_count} 公会玩家数量
    # {guild_max_member_count} 公会最大玩家数量
    formula: '{guild_money}*0.3+{guild_points}*0.5+{guild_member_count}*0.2'
  # 全员传送
  tp_all:
    # 允许发送请求的世界
    allowed_send_worlds:
      - '*'
    # 允许接收请求的世界
    allowed_receive_worlds:
      - '*'
    # 请求超时时间
    timeout: 15
    # 传送间隔限制
    interval: 60
    # 计次毫秒
    shift_count_interval: 1000
    # 触发次数
    shift_count: 3
    # 消耗公会银行金币
    cost:
      money: 500
      enabled: true
  upgrade:
    money:
      enabled: true
      # 金币升级公式
      formula: '1000*(1+0.05)^%GUILD_MAX_MEMBER_COUNT%'
      # 金币最大能升级到的人数
      max_member_count: 10
    points:
      enabled: true
      # 点券升级公式
      formula: '5*(1+0.05)^%GUILD_MAX_MEMBER_COUNT%'
      # 金币最大能升级到的人数
      max_member_count: 50
  # 赞助
  donate:
    input:
      cancel_string: 'c'
      wait_second: 30
    points:
      fee: 0.05
      min: 1
    money:
      fee: 0.1
      min: 10000
  # 默认最大管理员数量
  default_max_admin_count: 3
  # 默认最大成员数
  default_max_member_count: 5
  # 请求
  request:
    join:
      timeout: 3600 # 秒，请求加入超时
  # 公告
  announcement:
    default:
      - ' &d欢迎加入本公会~'
    # 换行符
    split_char: '#'
    # 最大公告数量
    max_count: 5
  # 创建
  create:
    input:
      cancel_str: '#QX' # 取消创建字符串
      wait_sec: 60 # 等待秒数
    # 公会名正则表达式
    name_regex: '[\u4e00-\u9fa5_a-zA-Z0-9_§]{1,10}'
    # 禁止公会重名
    no_duplication_name: true
    # 消费
    cost:
      # 金币
      money:
        amount: 1000
      # 点券
      points:
        amount: 100
      # 物品
      item:
        amount: 1 # 数量
        key_lore: '&a创建公会'
  # 解散
  dismiss:
    wait: 10 # 等待时间
    confirm_str: '确认'
  # 退出
  exit:
    wait: 10
    confirm_str: '确认'
  member:
    # 成员列表最多能预览多少
    most_show: 10
