VERSION: 2.0.0
# 是否开启数据统计
metrics_enabled: true
guild:
  default_icon:
    material: APPLE
    data: 0
    first_lore: '' # 用于支持 SX-Attribute 的物品
  # 排行榜
  ranking_list:
    # 计算公式，可用变量：
    # %GUILD_MONEY% 公会金币
    # %GUILD_POINTS% 公会点券
    # %GUILD_MEMBER_COUNT% 公会成员数
    # %GUILD_MAX_MEMBER_COUNT% 公会最大成员数
    formula: '%GUILD_MONEY%*0.3+%GUILD_POINTS%*0.5+%GUILD_MEMBER_COUNT%*0.2'
  # 全员传送
  tp_all:
    # 允许发送请求的世界
    allowed_send_worlds:
      - '*'
    # 允许接收请求的世界
    allowed_receive_worlds:
      - '*'
    # 请求超时时间
    timeout: 15
    # 传送间隔限制
    interval: 60
    # 计次毫秒
    shift_count_interval: 1000
    # 触发次数
    shift_count: 3
    # 消耗公会银行金币
    cost:
      money: 500
      enabled: true
  upgrade:
    money:
      enabled: true
      # 金币升级公式
      formula: '1000*(1+0.05)^%GUILD_MAX_MEMBER_COUNT%'
      # 金币最大能升级到的人数
      max_member_count: 10
    points:
      enabled: true
      # 点券升级公式
      formula: '5*(1+0.05)^%GUILD_MAX_MEMBER_COUNT%'
      # 金币最大能升级到的人数
      max_member_count: 50
  # 赞助
  donate:
    input:
      cancel_string: 'c'
      wait_second: 30
    points:
      fee: 0.05
      min: 1
    money:
      fee: 0.1
      min: 10000
  # 默认最大管理员数量
  default_max_admin_count: 3
  # 默认最大成员数
  default_max_member_count: 5
  # 请求
  request:
    join:
      timeout: 3600 # 秒，请求加入超时
  # 公告
  announcement:
    default:
      - ' &d欢迎加入本公会~'
    # 换行符
    split_char: '#'
    # 最大公告数量
    max_count: 5
  # 创建
  create:
    # 公会名正则表达式
    name_regex: '[\u4e00-\u9fa5_a-zA-Z0-9_§]{1,10}'
    # 消费
    cost:
      # 金币
      money:
        amount: 1000
      # 点券
      points:
        amount: 100
      # 物品
      item:
        amount: 1 # 数量
        key_lore: '&a创建公会'
  # 解散
  dismiss:
    wait: 10 # 等待时间
    confirm_str: '确认'
  member:
    # 成员列表最多能预览多少
    most_show: 10