config_version: 1.0.4
guild:
  def_max_member_count: 5
  create:
    name_regex: '[\\u4e00-\\u9fa5_a-zA-Z0-9_]{1,10}' # 注意转义
    name_not_valid_msg: '&c公会名只能由中文英文数字组成, 且长度大于1小于10个字符.'
    colored_no_per_msg: "&c你没有权限使用彩色代码作为宗门名."
    cost:
      money:
        amount: 1000
        enabled: true
      points:
        amount: 100
        enabled: true
      item:
        enabled: true
        key_lore: '创建宗会'
gui:
  main_gui:
    guild:
      display_name: '&a%GUILD_NAME%'
      lores:
        - '&7- &f等级 %GUILD_LEVEL%'
        - '&7- &f宗主 %GUILD_OWNER%'
        - '&7- &f人数 %GUILD_MEMBER_COUNT%/%GUILD_MAX_MEMBER_COUNT%'
        - '&7- &f创建时间 %GUILD_CREATION_TIME%'
    player_info_lores:
      - '&7- &f所在工会 %GUILD_PLAYER_IN%'
