config_version: 1.0.9
guild:
  #rank_formula: '%LEVEL% + %%'
  request:
    join:
      timeout: 3600 # 秒，请求加入超时
    invite:
      timeout: 300 # 秒，邀请超时
  announcement:
    split_char: '#' # 换行符
    max_count: 5 # 最大公告数量
  def_max_member_count: 5
  create:
    name_regex: '[\\u4e00-\\u9fa5_a-zA-Z0-9_§]{1,10}' # 注意转义
    name_not_valid_msg: '&c宗门名只能由中文英文数字组成, 且长度大于1小于10个字符.'
    colored_no_per_msg: "&c你没有权限使用彩色代码作为宗门名."
    cost:
      money:
        amount: 1000
        enabled: true
      points:
        amount: 100
        enabled: true
      item:
        enabled: true
        amount: 1
        key_lore: '创建宗门'
gui:
  main_gui:
    guild: # 工会信息
      display_name: '&a%GUILD_NAME%'
      lores:
        - '&b『&eTop.%GUILD_RANK%&b』'
        - ' '
        - '&7- &4等级 &b▹ &c%GUILD_LEVEL%'
        - '&7- &d宗主 &b▹ &d%GUILD_OWNER%'
        - '&7- &9人数 &b▹ &9%GUILD_MEMBER_COUNT%/%GUILD_MAX_MEMBER_COUNT%'
        - '&7- &a创建时间 &b▹ &a%GUILD_CREATION_TIME%'
    player_info_lores: # 个人信息
      - '&b『&e%player_name%&b』'
      - ''
      - '&7- &e宗门 &b▹ &e%GUILD_PLAYER_IN%'
