name: JulyGuild
main: com.github.julyss2019.mcsp.julyguild.JulyGuild
author: July_ss
version: 1.1.6
depend:
- JulyLibrary
- Vault
- PlayerPoints
- PlaceholderAPI
commands:
  jguild:
    aliases:
      - guild