name: JulyGuild
main: com.github.julyss2019.mcsp.julyguild.JulyGuild
author: July_ss
version: 1.1.9
depend:
- JulyLibrary
- Vault
softdepend:
- PlayerPoints
- PlaceholderAPI
commands:
  jguild:
    aliases:
      - guild
      - jg