name: JulyGuild
main: com.github.julyss2019.mcsp.julyguild.JulyGuild
author: July_ss
version: 2.0.1
softdepend:
- PlayerPoints
- JulyLibrary
- Vault
- PlaceholderAPI
commands:
  jguild:
    aliases:
      - guild
      - jg