name: JulyGuild
main: com.github.julyss2019.bukkit.plugins.julyguild.JulyGuild
author: July_ss
version: 2.0.0-RELEASE
softdepend:
- PlayerPoints
- JulyLibrary
- Vault
- PlaceholderAPI
commands:
  jguild:
    aliases:
      - guild
      - jg